import type { Exercise, Media } from "./model";
function exercise(
  id: string,
  name: string,
  split: "upper" | "lower",
  gear: Exercise["equipment"],
  visual: Exercise["visual"],
  cues: string[],
  pattern: string,
): Exercise {
  return {
    id,
    name,
    split,
    equipment: gear,
    visual,
    cues,
    pattern,
    sets: 2,
    reps: 10,
    rest: 90,
    weight: 0,
  };
}
export const catalog: Exercise[] = [
  exercise(
    "floor-press",
    "Dumbbell floor press",
    "upper",
    ["dumbbells"],
    "floor-press",
    [
      "Lie on the floor with knees bent and feet planted.",
      "Keep wrists above elbows. Press up, then lower under control.",
    ],
    "push",
  ),
  exercise(
    "db-row",
    "Supported dumbbell row",
    "upper",
    ["dumbbells"],
    "row",
    [
      "Use a stable support and keep your back comfortable.",
      "Pull your elbow toward your hip; lower slowly. Do each side.",
    ],
    "pull",
  ),
  exercise(
    "shoulder-press",
    "Dumbbell shoulder press",
    "upper",
    ["dumbbells"],
    "press",
    [
      "Start with weights near shoulder height.",
      "Press within a comfortable range without leaning back.",
    ],
    "push",
  ),
  exercise(
    "pull-apart",
    "Band pull-apart",
    "upper",
    ["loop-bands"],
    "band",
    [
      "Hold the band at chest height with soft elbows.",
      "Open your arms without shrugging. Return slowly.",
    ],
    "pull",
  ),
  exercise(
    "hammer-curl",
    "Hammer curl",
    "upper",
    ["dumbbells"],
    "curl",
    [
      "Keep palms facing inward and elbows by your sides.",
      "Curl without swinging, then lower slowly.",
    ],
    "arms",
  ),
  exercise(
    "band-curl",
    "Standing band curl",
    "upper",
    ["handle-bands"],
    "curl",
    [
      "Stand securely on the middle of the band.",
      "Keep elbows close and curl the handles without swinging.",
    ],
    "arms",
  ),
  exercise(
    "goblet-squat",
    "Goblet squat",
    "lower",
    ["dumbbells"],
    "squat",
    [
      "Hold one dumbbell close to your chest.",
      "Sit between your hips as far as comfortable, then stand.",
    ],
    "squat",
  ),
  exercise(
    "rdl",
    "Dumbbell Romanian deadlift",
    "lower",
    ["dumbbells"],
    "hinge",
    [
      "Soften your knees and send your hips backward.",
      "Keep weights close; stop before your back rounds or hurts.",
    ],
    "hinge",
  ),
  exercise(
    "reverse-lunge",
    "Reverse lunge",
    "lower",
    ["bodyweight"],
    "lunge",
    [
      "Step back and lower with control; use stable support if needed.",
      "Push through the front foot to return. Complete both sides.",
    ],
    "single-leg",
  ),
  exercise(
    "glute-bridge",
    "Glute bridge",
    "lower",
    ["bodyweight"],
    "bridge",
    [
      "Lie with knees bent and feet flat.",
      "Lift your hips without arching your lower back, then lower.",
    ],
    "hips",
  ),
  exercise(
    "calf-raise",
    "Standing calf raise",
    "lower",
    ["bodyweight"],
    "calf",
    [
      "Stand beside a stable support.",
      "Rise onto the balls of your feet, pause, then lower slowly.",
    ],
    "calves",
  ),
  exercise(
    "lateral-walk",
    "Mini-band lateral walk",
    "lower",
    ["mini-bands"],
    "band",
    [
      "Place the band above your knees with a small bend in your hips.",
      "Take controlled side steps. Complete the reps each way.",
    ],
    "hips",
  ),
];
export const initialMedia: Media[] = [
  {
    id: "morning",
    title: "Your morning routine",
    area: "full-body",
    source: "https://supplewarriors.com/freeroutinee",
    embed: "https://www.youtube-nocookie.com/embed/0xl1vJmTsMk",
    creator: "Tom Fysh · Supple Warriors",
    reviewed: false,
    note: "Follow along at a comfortable pace. Pause whenever you need.",
  },
  {
    id: "DdZh_w8oLSY",
    title: "Hips after sitting",
    area: "hips",
    source: "https://www.instagram.com/reel/DdZh_w8oLSY/",
    embed: "https://www.instagram.com/reel/DdZh_w8oLSY/embed/",
    creator: "Anthony Green",
    reviewed: true,
    note: "Lunge rotation, seated hip switches, and kneeling hip movement. Stay within a comfortable range.",
  },
  {
    id: "DdRIrlwowu_",
    title: "Upper-back movement",
    area: "upper-back",
    source: "https://www.instagram.com/reel/DdRIrlwowu_/",
    embed: "https://www.instagram.com/reel/DdRIrlwowu_/embed/",
    creator: "Anthony Green",
    reviewed: true,
    note: "Standing rotation, shoulder rotation, and upper-back extension. Move slowly and comfortably.",
  },
  {
    id: "DdZBFgZI4S-",
    title: "Neck movement & control",
    area: "neck",
    source: "https://www.instagram.com/reel/DdZBFgZI4S-/",
    embed: "https://www.instagram.com/reel/DdZBFgZI4S-/embed/",
    creator: "Anthony Green",
    reviewed: false,
    note: "Includes a ball and bench that are not in your equipment list. Reference only; not assigned to workouts.",
  },
];
