import type { AppData } from "./types";

// Handoff catalog. Server/migration input only; never imported by the client.
export const SEED: AppData = {
  schemaVersion: 2,
  balanceSet: false,
  currentBalance: 0,
  transactions: [],
  plannedPayments: [],
  planEntries: [
    // Bills supplied by Jerami. Dates are informational, never automatic payments.
    {
      id: "b1",
      name: "Rent",
      amount: 700,
      dueDate: "",
      recurrence: "monthly",
      dueDay: 1,
      notes: "Due by the 1st",
      planType: "bill",
      isActive: true,
    },
    {
      id: "b2",
      name: "Frontier WiFi",
      amount: 69.99,
      dueDate: "2026-09-04",
      recurrence: "none",
      notes: "My half. First payment September 4; ongoing schedule not set.",
      planType: "bill",
      isActive: true,
    },
    {
      id: "b3",
      name: "Light Bill",
      amount: 0,
      amountDisplay: "around $77–$80",
      dueDate: "",
      recurrence: "monthly",
      dueDay: 27,
      notes: "Usually due on the 27th",
      planType: "bill",
      isActive: true,
      isApproximate: true,
    },
    {
      id: "b4",
      name: "Constellation Academy",
      amount: 340,
      dueDate: "",
      recurrence: "semimonthly",
      dueDay: 1,
      secondDueDay: 15,
      notes: "Usually the 1st and 15th; confirm with provider",
      planType: "bill",
      isActive: true,
    },
    {
      id: "b5",
      name: "Direct Auto",
      amount: 0,
      amountDisplay: "around $150–$160",
      dueDate: "",
      notes:
        "Due date and frequency not yet provided. Enter the actual amount when adding to the cycle.",
      planType: "bill",
      isActive: true,
      isApproximate: true,
    },

    // ── Subscriptions ──────────────────────────────────────────────────────────
    {
      id: "s1",
      name: "ChatGPT",
      amount: 20,
      dueDate: "",
      recurrence: "monthly",
      notes: "",
      planType: "subscription",
      isActive: true,
    },
    {
      id: "s2",
      name: "Figma",
      amount: 20,
      dueDate: "",
      recurrence: "monthly",
      notes: "",
      planType: "subscription",
      isActive: true,
    },
    {
      id: "s3",
      name: "Raycast",
      amount: 10,
      dueDate: "",
      recurrence: "monthly",
      notes: "",
      planType: "subscription",
      isActive: true,
    },
    {
      id: "s4",
      name: "Google Workspace",
      amount: 0,
      amountDisplay: "around $8",
      dueDate: "",
      recurrence: "monthly",
      notes: "",
      planType: "subscription",
      isActive: true,
      isApproximate: true,
    },
    {
      id: "s5",
      name: "Screen Studio",
      amount: 0,
      amountDisplay: "around $15",
      dueDate: "",
      recurrence: "monthly",
      notes: "",
      planType: "subscription",
      isActive: true,
      isApproximate: true,
    },
    {
      id: "s6",
      name: "Envato Elements",
      amount: 23,
      dueDate: "",
      recurrence: "monthly",
      notes: "",
      planType: "subscription",
      isActive: true,
    },
    {
      id: "s7",
      name: "Mirage Host",
      amount: 5,
      dueDate: "",
      recurrence: "monthly",
      notes: "",
      planType: "subscription",
      isActive: true,
    },
    {
      id: "s8",
      name: "Gym membership",
      amount: 16,
      dueDate: "",
      recurrence: "monthly",
      notes: "",
      planType: "subscription",
      isActive: true,
      tag: "upcoming · not started",
    },

    // ── Advances (15 exact records) ────────────────────────────────────────────
    {
      id: "a1",
      name: "Cleo",
      amount: 104.98,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 104.98,
    },
    {
      id: "a2",
      name: "Albert",
      amount: 150.0,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 150.0,
    },
    {
      id: "a3",
      name: "Brigit",
      amount: 53.0,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 53.0,
    },
    {
      id: "a4",
      name: "Cash App",
      amount: 253.84,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 253.84,
    },
    {
      id: "a5",
      name: "Chime",
      amount: 95.0,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 95.0,
    },
    {
      id: "a6",
      name: "Credit Genie",
      amount: 59.49,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 59.49,
    },
    {
      id: "a7",
      name: "Dave",
      amount: 130.17,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 130.17,
    },
    {
      id: "a8",
      name: "Earnin",
      amount: 50.0,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 50.0,
    },
    {
      id: "a9",
      name: "Grant",
      amount: 37.5,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 37.5,
    },
    {
      id: "a10",
      name: "Klarna",
      amount: 419.39,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 419.39,
    },
    {
      id: "a11",
      name: "Money Lion",
      amount: 92.49,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 92.49,
    },
    {
      id: "a12",
      name: "Stream",
      amount: 60.0,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 60.0,
    },
    {
      id: "a13",
      name: "Tilt",
      amount: 27.0,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 27.0,
    },
    {
      id: "a14",
      name: "Vola",
      amount: 70.0,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 70.0,
    },
    {
      id: "a15",
      name: "Zip",
      amount: 96.56,
      dueDate: "",
      notes: "",
      planType: "advance",
      isActive: true,
      balance: 96.56,
    },

    // ── Debts ──────────────────────────────────────────────────────────────────
    {
      id: "d1",
      name: "InstaLoan",
      amount: 3205.78,
      dueDate: "",
      notes: "45.80% APR. Single-payment / renewable.",
      planType: "debt",
      isActive: true,
      balance: 3205.78,
    },
    {
      id: "d2",
      name: "HSN/Synchrony",
      amount: 769.24,
      paymentAmount: 51.6,
      dueDate: "",
      recurrence: "monthly",
      dueDay: 15,
      notes: "Next payment $51.60 on the 15th. No August 31 payment.",
      planType: "debt",
      isActive: true,
      balance: 769.24,
    },
    {
      id: "d3",
      name: "Macy's PRA",
      amount: 333.21,
      paymentAmount: 111.07,
      dueDate: "",
      recurrence: "monthly",
      notes: "$111.07 × 3; pending",
      planType: "debt",
      isActive: true,
      balance: 333.21,
      tag: "pending",
    },
    {
      id: "d4",
      name: "Apple",
      amount: 4138.97,
      paymentAmount: 160,
      dueDate: "",
      notes: "$160 standard monthly payment; settlement is a separate option",
      planType: "debt",
      isActive: true,
      balance: 4138.97,
      settlementAmount: 2938.67,
      settlementDisplay: "$2,938.67",
    },
    // Approximate debts — no numeric balance, no midpoint amount, isApproximate: true
    {
      id: "d5",
      name: "Discover",
      amount: 0,
      amountDisplay: "around $10,000",
      dueDate: "",
      notes: "",
      planType: "debt",
      isActive: true,
      isApproximate: true,
      balance: 10000,
      balanceQualifier: "around",
      balanceDisplay: "around $10,000",
    },
    {
      id: "d6",
      name: "USAA",
      amount: 0,
      dueDate: "",
      notes: "",
      planType: "debt",
      isActive: true,
      balance: 1035,
    },
    {
      id: "d7",
      name: "2024 taxes",
      amount: 0,
      amountDisplay: "around $8,500",
      dueDate: "",
      notes: "",
      planType: "debt",
      isActive: true,
      isApproximate: true,
      balance: 8500,
      balanceQualifier: "around",
      balanceDisplay: "around $8,500",
    },
    {
      id: "d8",
      name: "Spectrum",
      amount: 0,
      amountDisplay: "around $150–$350",
      dueDate: "",
      notes: "",
      planType: "debt",
      isActive: true,
      isApproximate: true,
      balance: 150,
      balanceHigh: 350,
      balanceQualifier: "range",
      balanceDisplay: "around $150–$350",
    },
    {
      id: "d9",
      name: "GEICO",
      amount: 260,
      dueDate: "",
      notes: "",
      planType: "debt",
      isActive: true,
      balance: 260,
      tag: "lapsed",
    },
  ],
};
