import assert from 'node:assert/strict';
import {assertPhotoCoverage, assertPush, assertVisibleSubject, visibleSubjectBounds, assertHeadPattern} from '../lib/lineups/framing.mjs';
const scene = {id:'photo', width:1920, height:1080, absoluteTransform:[[1,0,0],[0,1,0]]};
const image = {id:'image', width:1920, height:1080, absoluteTransform:scene.absoluteTransform, fills:[{mode:'CROP',transform:[[1,0,0],[0,1,0]],size:{width:1920,height:1080}}], tracks:{SCALE_XY:[{time:0,value:{value:{x:1,y:1}},easing:'LINEAR'},{time:6.5,value:{value:{x:1.025,y:1.025}},easing:'LINEAR'}]}};
assertPhotoCoverage(scene,image);assertPush(image);
assert.throws(()=>assertPhotoCoverage(scene,{...image,width:1919}),/uncovered/);
assert.throws(()=>assertPhotoCoverage(scene,{...image,fills:[{...image.fills[0],mode:'FIT'}]}),/FIT/);
assert.throws(()=>assertPhotoCoverage(scene,image,[0.14,0,0.86,1]),/usable photograph/);
const zoomOut=structuredClone(image);zoomOut.tracks.SCALE_XY[0].value.value={x:.99,y:.99};assert.throws(()=>assertPush(zoomOut),/100%/);
const dip=structuredClone(image);dip.tracks.SCALE_XY.splice(1,0,{time:2,value:{value:{x:.98,y:.98}},easing:'LINEAR'});assert.throws(()=>assertPush(dip),/shrinks/);
const second=structuredClone(image);second.tracks.SCALE_XY.forEach(k=>k.time+=5);assertPush(second);
const bounds={x:200,y:300,width:600,height:900};const subject={id:'alpha',hasAlpha:true,current:bounds,baseline:bounds};assertVisibleSubject(subject);
assert.throws(()=>assertVisibleSubject({...subject,current:{...bounds,width:720}}),/over 10%/);
assert.throws(()=>assertVisibleSubject({...subject,current:{...bounds,y:450}}),/moved/);
assert.throws(()=>assertVisibleSubject({...subject,hasAlpha:false}),/true alpha/);
assert.deepEqual(visibleSubjectBounds(scene,image,[.25,.25,.75,.75]),{x:480,y:270,width:960,height:540});
assertHeadPattern({kind:'three',left:{top:330},center:{top:280},right:{top:320}});
assert.throws(()=>assertHeadPattern({kind:'three',left:{top:200},center:{top:280},right:{top:320}}),/highest/);
assert.throws(()=>assertHeadPattern({kind:'two',left:{top:340,outerMargin:150},right:{top:340,outerMargin:10}}),/padding/);
console.log('Framing regressions passed: undersized photo, FIT, baked bars, zoom-out, motion dip, subject scale, vertical shift, missing alpha');
