#!/usr/bin/env python3
"""Build the iPhone capture shortcut; never embed a credential."""
import pathlib
import plistlib
import subprocess


def uuid():
    return subprocess.check_output(["/usr/bin/uuidgen"], text=True).strip().upper()


actions = []


def action(identifier, **parameters):
    identifier = "is.workflow.actions." + identifier
    parameters.setdefault("UUID", uuid())
    actions.append({"WFWorkflowActionIdentifier": identifier, "WFWorkflowActionParameters": parameters})
    return {"Type": "ActionOutput", "OutputUUID": parameters["UUID"], "OutputName": {
        "ask": "Provided Input", "dictionary": "Dictionary", "gettext": "Text",
        "runsshscript": "Shell Script Result", "detect.dictionary": "Dictionary",
        "getvalueforkey": "Dictionary Value",
    }.get(identifier.rsplit(".", 1)[-1], "Result")}


def attachment(output):
    return {"Value": output, "WFSerializationType": "WFTextTokenAttachment"}


def text(value):
    if isinstance(value, dict):
        return {"Value": {"string": "\ufffc", "attachmentsByRange": {"{0, 1}": value}}, "WFSerializationType": "WFTextTokenString"}
    return {"Value": {"string": value}, "WFSerializationType": "WFTextTokenString"}


def comment(value):
    action("comment", WFCommentActionText=value)


def begin(output, code, literal=None):
    group = uuid()
    parameters = {"GroupingIdentifier": group, "WFControlFlowMode": 0, "WFCondition": code,
                  "WFInput": {"Type": "Variable", "Variable": attachment(output)}}
    if literal is not None:
        parameters["WFConditionalActionString"] = literal
    action("conditional", **parameters)
    return group


def end(group):
    action("conditional", GroupingIdentifier=group, WFControlFlowMode=2)


def empty_guard(output):
    comment("- Check the preceding input.\n- Stop if empty.")
    group = begin(output, 101)
    action("exit")
    end(group)


def request(fields):
    items = []
    for key, value in fields.items():
        encoded = {"Value": value, "WFSerializationType": "WFNumberSubstitutableState"} if isinstance(value, bool) else text(value)
        items.append({"WFItemType": 4 if isinstance(value, bool) else 0, "WFKey": text(key), "WFValue": encoded})
    dictionary = action("dictionary", WFItems={"Value": {"WFDictionaryFieldValueItems": items}, "WFSerializationType": "WFDictionaryFieldValue"})
    serialized = action("gettext", WFTextActionText=text(dictionary))
    return action("runsshscript", WFSSHHost="100.99.124.26", WFSSHPort="22", WFSSHUser="singleton23",
                  WFSSHAuthenticationType="SSH Key", WFInput=attachment(serialized),
                  WFSSHScript='"$HOME/Library/Application Support/Singleton Systems/api-key-intake/api-key-intake" --stdin')


def status(result):
    parsed = action("detect.dictionary", WFInput=attachment(result))
    field = action("getvalueforkey", WFInput=attachment(parsed), WFDictionaryKey="status", WFGetDictionaryValueType="Value")
    return action("gettext", WFTextActionText=text(field))


comment("Save a named API key to the Mac login Keychain over Tailscale SSH. Requires the Mac to be online and its login Keychain unlocked. Authorize this iPhone's Shortcuts SSH public key once. Values enter at runtime and travel through SSH stdin.")
comment("Shortcuts generated by Shortcuts Playground. May contain mistakes. Always check the shortcut's actions first.\n\nThis shortcut was created via the following user prompt:\n\n> I want this to match how my other Singleton Systems shortcuts are stored, with iPhone capture and a Mac Raycast command.")
name = action("ask", WFAskActionPrompt="Enter the key name (for example SCRAPECREATORS_API_KEY):", WFInputType="Text")
empty_guard(name)
comment("--- CHECK MAC AND EXISTING KEY ---")
checked = request({"operation": "check", "name": name})
checked_status = status(checked)
comment("- Read the Mac's status.\n- Show a safe error and stop before asking for the API key.")
group = begin(checked_status, 4, "error")
action("showresult", Text=text(checked))
action("exit")
end(group)
comment("- If the key exists, confirm replacement.\n- Cancel stops the shortcut.")
group = begin(checked_status, 4, "exists")
action("alert", WFAlertActionTitle="Replace existing key?", WFAlertActionMessage=text(name), WFAlertActionCancelButtonShown=True)
end(group)
comment("--- SAVE API KEY ---")
value = action("ask", WFAskActionPrompt="Paste the API key:", WFInputType="Text")
empty_guard(value)
saved = request({"operation": "save", "name": name, "value": value, "replace": True})
saved_status = status(saved)
comment("- Only report success when the Mac confirms saved.\n- Errors contain no API key.")
group = begin(saved_status, 4, "saved")
action("showresult", Text={"Value": {"string": "Saved: \ufffc", "attachmentsByRange": {"{7, 1}": name}}, "WFSerializationType": "WFTextTokenString"})
action("conditional", GroupingIdentifier=group, WFControlFlowMode=1)
action("showresult", Text=text(saved))
end(group)

workflow = {"WFWorkflowActions": actions, "WFWorkflowName": "S.System Save API Key",
            "WFWorkflowClientVersion": "2700.0.4", "WFWorkflowHasOutputFallback": False,
            "WFWorkflowMinimumClientVersion": 900, "WFWorkflowMinimumClientVersionString": "900",
            "WFWorkflowIcon": {"WFWorkflowIconGlyphNumber": 59760, "WFWorkflowIconStartColor": 2071128575},
            "WFWorkflowImportQuestions": [], "WFWorkflowInputContentItemClasses": [],
            "WFWorkflowOutputContentItemClasses": [], "WFWorkflowTypes": []}
target = pathlib.Path(__file__).with_name("S.System Save API Key.xml")
target.write_bytes(plistlib.dumps(workflow, fmt=plistlib.FMT_XML))
print(f"Built {len(actions)} actions: {target}")
